CREATE TABLE IF NOT EXISTS `PREFIX_ntresellerclub_price_history` (
  `id_ntresellerclub_price_history` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `provider_code` VARCHAR(64) NOT NULL,
  `product_type` VARCHAR(50) NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `old_cost_price` DECIMAL(20,6) DEFAULT NULL,
  `new_cost_price` DECIMAL(20,6) DEFAULT NULL,
  `old_sale_price` DECIMAL(20,6) DEFAULT NULL,
  `new_sale_price` DECIMAL(20,6) DEFAULT NULL,
  `currency` VARCHAR(10) DEFAULT NULL,
  `change_source` VARCHAR(64) DEFAULT 'system',
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id_ntresellerclub_price_history`),
  KEY `idx_price_history_provider` (`provider_code`),
  KEY `idx_price_history_code` (`code`),
  KEY `idx_price_history_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PREFIX_ntresellerclub_exchange_rate_history` (
  `id_ntresellerclub_exchange_rate_history` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_currency` VARCHAR(10) NOT NULL,
  `to_currency` VARCHAR(10) NOT NULL,
  `old_rate` DECIMAL(20,6) DEFAULT NULL,
  `new_rate` DECIMAL(20,6) NOT NULL,
  `change_source` VARCHAR(64) DEFAULT 'admin',
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id_ntresellerclub_exchange_rate_history`),
  KEY `idx_exchange_pair` (`from_currency`, `to_currency`),
  KEY `idx_exchange_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PREFIX_ntresellerclub_operation_queue` (
  `id_ntresellerclub_operation_queue` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_order` INT UNSIGNED DEFAULT NULL,
  `id_customer` INT UNSIGNED DEFAULT NULL,
  `id_service` INT UNSIGNED DEFAULT NULL,
  `provider_code` VARCHAR(64) NOT NULL,
  `service_type` VARCHAR(50) NOT NULL,
  `action` VARCHAR(64) NOT NULL,
  `priority` INT UNSIGNED NOT NULL DEFAULT 3,
  `payload_json` MEDIUMTEXT NULL,
  `response_json` MEDIUMTEXT NULL,
  `status` VARCHAR(50) DEFAULT 'pending',
  `retry_count` INT UNSIGNED DEFAULT 0,
  `max_retries` INT UNSIGNED DEFAULT 3,
  `last_error` TEXT NULL,
  `lock_token` VARCHAR(128) DEFAULT NULL,
  `locked_at` DATETIME DEFAULT NULL,
  `processed_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id_ntresellerclub_operation_queue`),
  KEY `idx_queue_status` (`status`),
  KEY `idx_queue_pending` (`status`, `priority`, `id_ntresellerclub_operation_queue`),
  KEY `idx_queue_provider` (`provider_code`),
  KEY `idx_queue_order` (`id_order`),
  KEY `idx_queue_service` (`id_service`),
  KEY `idx_queue_retry` (`retry_count`),
  KEY `idx_queue_lock` (`lock_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PREFIX_ntresellerclub_contact_profile` (
  `id_ntresellerclub_contact_profile` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_customer` INT UNSIGNED NOT NULL,
  `profile_type` VARCHAR(50) DEFAULT 'personal',
  `company_name` VARCHAR(255) DEFAULT NULL,
  `first_name` VARCHAR(128) DEFAULT NULL,
  `last_name` VARCHAR(128) DEFAULT NULL,
  `tax_number` VARCHAR(64) DEFAULT NULL,
  `tax_office` VARCHAR(128) DEFAULT NULL,
  `tc_number` VARCHAR(64) DEFAULT NULL,
  `address` TEXT NULL,
  `city` VARCHAR(128) DEFAULT NULL,
  `state` VARCHAR(128) DEFAULT NULL,
  `country_iso` VARCHAR(5) DEFAULT NULL,
  `postcode` VARCHAR(32) DEFAULT NULL,
  `phone` VARCHAR(64) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `is_default` TINYINT(1) DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id_ntresellerclub_contact_profile`),
  KEY `idx_contact_profile_customer` (`id_customer`),
  KEY `idx_contact_profile_default` (`id_customer`, `is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
